a = input('Digite um algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alphabético? ', a.isalpha())
print('É alphanumérico? ', a.isalnum())
print('Está com letras maiúsculas? ', a.isupper())
print('Está com letras minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())